---
# config.yaml
# this file contains xpaths and relevant config variables
# based on the configuration you choose for getting
# your results from flight_price_trends.

permitted_countries:
  - de
  - us
  - uk
permitted_flex:
  '-1': 'flexible-1day-after'
  '+1': 'flexible-1day-before'
  '1': 'flexible-1day'
  '2': 'flexible-2days'
  '3': 'flexible-3days'
permitted_journey_types:
  - 'one_way'
  - 'round_trip'
  - 'multi_city'
  - 'city_options-one_way'
  - 'city_options-round_trip'
  # - 'city_options-multi_city'
permitted_sort_by:
  - 'price'
  - 'duration_leg_*'
  - 'duration_total'
  - 'n_stops_leg_*'
  - 'n_stops_total'
max_city_options: 6
country:
  de:
    base_url: 'https://kayak.de/flights/'
    xpaths: 
      all_results: '//*[@id="listWrapper"]/div/div[2]/div'
      result_blocks: '//*[@id="listWrapper"]/div/div[2]/div/div[*]'
  us:
    base_url: 'https://kayak.com/flights/'
    xpaths: 
      all_results: '//*[@id="listWrapper"]/div/div[2]/div'
      result_blocks: '//*[@id="c8C-J"]/div/div/div[*]'
  uk: 
    base_url: 'https://kayak.co.uk/flights/'
    currency_symbol: '£'
    xpaths: 
      cookie_decline_button: '//*[@id="portal-container"]/div/div[2]/div/div/div[2]/div/div[2]/button'
      all_results: '//*[@id="listWrapper"]/div/div[2]/div'
      # result_blocks: '//*[@id="wNTH"]/div/div/div[*]'
      # result_blocks: '//*[@id="listWrapper"]/div/div[2]/div/div[*]'
      # result_blocks: '//*[@id="Qyf9"]/div/div/div[2]'
      result_blocks: '/html/body/div[2]/div[1]/main/div/div[2]/div[2]/div[1]/div[2]/div[1]/div[2]/div[5]/div[2]/div/div/div/div[*]'
      # show_more_button: '//*[@id="listWrapper"]/div/div[3]/div'
      show_more_button: '/html/body/div[2]/div[1]/main/div/div[2]/div[2]/div[1]/div[2]/div[1]/div[3]/div[2]/div/div/div'
    css_selectors:
      progress_bar: "[id*='-progress-bar'][class*='progress-bar-sticky']"
      result_blocks: "[class*='nrc6']"
      show_more_button: "[class*='-button show-more-button']"
insert_map:
  journeys: 
    - journey_id
    - search_id
    - n_legs
    - cabin_baggage
    - checked_baggage
    - class
    - airline
  legs:
    - leg_id
    - journey_id
    - leg_number
    - departure_time
    - arrival_time
    - departure_airport
    - arrival_airport
    - duration
    - n_stops
    - stopover_airports
    - distance_nominal
    - distance_absolute
  prices:
    - journey_id
    - price
    - currency
    - created_at
  flight_searches:
    - search_id
    - journey_type
    - origin
    - destination
    - leave_date
    - return_date
    - flex
  compound_airport_codes:
    - compound_code
    - airport_code
